language: node_js
node_js:
  - "10.14.1"
jobs:
  include:
    - stage: "Build"
      script: npm run build
      name: "Building application"
    - stage: "Test"
      script: npm run test
      name: "Visual Tests"
